/**
 * Alchemy Configuration
 * Generated by alchemy-migrator
 * Generated at: 2025-12-18T21:45:31.817Z
 *
 * Learn more: https://alchemy.run
 */

import alchemy from "alchemy";
import {
	DurableObjectNamespace,
	KVNamespace,
	Queue,
	Worker,
} from "alchemy/cloudflare";

const app = await alchemy("mail-to-ai");

export const cache_kv = await KVNamespace("cache_kv", {
	title: `${app.name}-cache_kv`,
	adopt: true,
});

export const email_queue = await Queue("email_queue", {
	name: `${app.name}-email-processing`,
	adopt: true,
});

export const email_dlq = await Queue("email_dlq", {
	name: `${app.name}-email-processing-dlq`,
	adopt: true,
});

export const echo_agent = DurableObjectNamespace("echo_agent", {
	className: "EchoAgent",
	scriptName: undefined,
});

export const info_agent = DurableObjectNamespace("info_agent", {
	className: "InfoAgent",
	scriptName: undefined,
});

export const worker = await Worker("mail-to-ai", {
	name: `${app.name}-worker`,
	entrypoint: "src/index.ts",
	compatibilityDate: "2024-12-01",
	compatibilityFlags: ["nodejs_compat"],
	observability: undefined,
	// bindings: {
	// 	CACHE_KV: cache_kv,
	// 	EMAIL_QUEUE: email_queue,
	// 	EMAIL_DLQ: email_dlq,
	// 	ECHO_AGENT: echo_agent,
	// 	INFO_AGENT: info_agent,
	// 	ALLOWED_DOMAIN: "mail-to-ai.com",
	// },
	// eventSources: [
	// 	{
	// 		queue: email - processing,
	// 		settings: {
	// 			batchSize: 10,
	// 			maxWaitTimeMs: 30,
	// 			maxRetries: 3,
	// 			maxConcurrency: undefined,
	// 			deadLetterQueue: "email-processing-dlq",
	// 		},
	// 	},
	// ],
});

console.log(worker.url);

await app.finalize();
