/**
 * Base agent class for all email agents
 */

import Anthropic from '@anthropic-ai/sdk';
import type { ParsedEmail, EmailReply, AgentResult } from '../types';

export abstract class BaseAgent {
  protected email: ParsedEmail;
  protected anthropic: Anthropic;
  protected domain: string;

  constructor(email: ParsedEmail, apiKey: string, domain: string) {
    this.email = email;
    this.anthropic = new Anthropic({ apiKey });
    this.domain = domain;
  }

  /**
   * Each agent must implement its system prompt
   */
  abstract getSystemPrompt(): string;

  /**
   * Get the agent's email address for replies
   */
  abstract getAgentAddress(): string;

  /**
   * Get the agent's display name
   */
  getAgentName(): string {
    return 'AI Agent';
  }

  /**
   * Override for agents that need tools (web search, etc.)
   */
  protected getTools(): Anthropic.Tool[] {
    return [];
  }

  /**
   * Build the user message from the email
   */
  protected buildUserMessage(): string {
    return `Subject: ${this.email.subject}

From: ${this.email.from.name || this.email.from.email} <${this.email.from.email}>

Message:
${this.email.body}`.trim();
  }

  /**
   * Process the email and generate a response
   */
  async process(): Promise<string> {
    const tools = this.getTools();

    const response = await this.anthropic.messages.create({
      model: 'claude-sonnet-4-20250514',
      max_tokens: 4096,
      system: this.getSystemPrompt(),
      messages: [
        {
          role: 'user',
          content: this.buildUserMessage(),
        },
      ],
      ...(tools.length > 0 && { tools }),
    });

    // Extract text from response
    const textBlock = response.content.find((block) => block.type === 'text');
    return textBlock?.text || 'Sorry, I could not generate a response.';
  }

  /**
   * Generate the full email reply
   */
  async generateReply(): Promise<AgentResult> {
    try {
      const responseBody = await this.process();

      const reply: EmailReply = {
        to: this.email.from.email,
        from: `${this.getAgentName()} <${this.getAgentAddress()}>`,
        subject: this.email.subject.startsWith('Re:')
          ? this.email.subject
          : `Re: ${this.email.subject}`,
        body: responseBody,
        html: this.formatAsHtml(responseBody),
        inReplyTo: this.email.messageId,
        references: [...this.email.references, this.email.messageId],
      };

      return { success: true, reply };
    } catch (error) {
      console.error(`Agent ${this.constructor.name} failed:`, error);
      return {
        success: false,
        error: error instanceof Error ? error.message : 'Unknown error',
      };
    }
  }

  /**
   * Convert plain text response to HTML
   */
  protected formatAsHtml(text: string): string {
    // Convert markdown-style formatting
    let html = text
      // Code blocks
      .replace(/```(\w*)\n([\s\S]*?)```/g, '<pre><code>$2</code></pre>')
      // Inline code
      .replace(/`([^`]+)`/g, '<code>$1</code>')
      // Bold
      .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
      // Italic
      .replace(/\*([^*]+)\*/g, '<em>$1</em>')
      // Links
      .replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2">$1</a>');

    // Convert paragraphs
    const paragraphs = html.split('\n\n');
    const htmlParagraphs = paragraphs.map((p) => {
      // Don't wrap pre blocks in paragraphs
      if (p.includes('<pre>')) return p;
      return `<p>${p.replace(/\n/g, '<br>')}</p>`;
    });

    return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      line-height: 1.6;
      color: #333;
      max-width: 600px;
    }
    p { margin: 1em 0; }
    code {
      background: #f4f4f4;
      padding: 2px 6px;
      border-radius: 3px;
      font-family: 'Monaco', 'Menlo', monospace;
    }
    pre {
      background: #f4f4f4;
      padding: 12px;
      border-radius: 6px;
      overflow-x: auto;
    }
    pre code { background: none; padding: 0; }
    a { color: #0066cc; }
  </style>
</head>
<body>
  ${htmlParagraphs.join('\n  ')}

  <hr style="margin: 2em 0; border: none; border-top: 1px solid #ddd;">
  <p style="color: #666; font-size: 0.9em;">
    This email was generated by an AI agent. Reply to continue the conversation.
  </p>
</body>
</html>`.trim();
  }
}
